name: Update News JSON

on:
  schedule:
    # Runs every day at 7:00 AM UTC
    - cron: '0 7 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Update new.json with sample news
      run: |
        echo '[{"title": "Automated news update from GitHub Actions!"},{"title": "More news will appear here."}]' > new.json

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add new.json
        git commit -m "Automated update of news JSON" || echo "No changes to commit"
        git push
