yaml
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add new.json
        git commit -m "Automated update of news JSON" || echo "No changes to commit"
        git pull --rebase origin main
        git push origin main
